### ISSUE TITLE
Change Team page look.

### ISSUE THREAD

**Issue by Darshilp326** [Infinito-IIT-Patna/Infinito2020#11]

**Comment by ghost** [comment]
which languange i have to use ? Can I try this ?

**Comment by Darshilp326** [comment]
@rupakbiswas2304 html css javascript

**Comment by StrixROX** [comment]
i'll work on this

**Comment by StrixROX** [comment]
is this issue still up for grabs?

**Comment by debarghya472** [comment]
go for it

**Comment by StrixROX** [comment]
So does this look ok?

![image](https://user-images.githubusercontent.com/40167899/103313879-62768500-4a47-11eb-89b1-012e535db0bf.png)
![image](https://user-images.githubusercontent.com/40167899/103313946-905bc980-4a47-11eb-8c9b-6d89ddc9e6ea.png)

![image](https://user-images.githubusercontent.com/40167899/103313906-75895500-4a47-11eb-939f-ab9a6d844c6c.png)
![image](https://user-images.githubusercontent.com/40167899/103313912-7a4e0900-4a47-11eb-9bf3-7b7856c1c95c.png)

**Comment by debarghya472** [comment]
The design is really fab!! Go and PR it.

Make the phone no. clickable because I'm assuming most of the people would access our site via phone.
So, on clicking the phone icon would intent the phone no. to the phone app present in the phone. 
I think it would be more useful that way. 

It's just my suggestion, do what suits you.

**Comment by Darshilp326** [comment]
@debarghya472 Give him new team members list and photos.

**Comment by StrixROX** [comment]
I think having the call icon in place of the contact no. will be bad for accessibility of the contact no.
The more steps there are to get to something, the less likely the user is to try to get to it.

So I tried something. Please see if this is any better or if I should just stick to what was there earlier.

https://user-images.githubusercontent.com/40167899/103341280-7e604200-4aac-11eb-85c8-f38b1f1eff90.mp4

PS: That call icon in the right side of url bar indicates that a call request is sent.

**Comment by debarghya472** [comment]
Thats really nice! Update the new team members by today!!
