### ISSUE TITLE
Need an "Error 404" page

### ISSUE THREAD

**Issue by StrixROX** [Infinito-IIT-Patna/Infinito2020#17]
Exactly what the title says. Make a nice "Error 404" page.

**Comment by rdev12** [comment]
Can I take up this?

**Comment by Darshilp326** [comment]
@RishikeshDevanathan go for it!
Try to find some good designs online!

**Comment by rdev12** [comment]
I did this partly from scratch:
![image](https://user-images.githubusercontent.com/20983723/103269486-f6ab0280-49db-11eb-85e4-19412f356245.png)

Is this okay or do you want it to be more dynamic? @Darshilp326

**Comment by debarghya472** [comment]
Its Good! Go ahead create a pull request. (In a different branch)

**Comment by Darshilp326** [comment]
@RishikeshDevanathan check for responsiveness!

**Comment by rdev12** [comment]
There is a small problem with responsiveness, I'll try to fix it and create the pull request soon @Darshilp326
