### ISSUE TITLE
Update logo and poster on home page

### ISSUE THREAD

**Issue by Darshilp326** [Infinito-IIT-Patna/Infinito2020#2]

**Comment by rdev12** [comment]
I'll take up this. I'm just a beginner but this seems doable

**Comment by Darshilp326** [comment]
@RishikeshDevanathan for this you need to setup database.

**Comment by rdev12** [comment]
Can you tell me what exactly to do so that I can try it out? @Darshilp326

**Comment by debarghya472** [comment]
@RishikeshDevanathan  contact me I'll help you
