### ISSUE TITLE
Change the written content in Home page.

### ISSUE THREAD

**Issue by debarghya472** [Infinito-IIT-Patna/Infinito2020#29]
- Write new content below this issue
- Get it approved and change it in the website with proper formatting. i.e. using Html tags like" <p, br>" etc.

**Comment by 4d4r5h** [comment]
I want to work on this.

**Comment by debarghya472** [comment]
Get on with it. Just a suggestion that this year Infinito will be virtual mainly online games and guest talks. The write up would be based on that. 

If u need help contact us!

**Comment by 4d4r5h** [comment]
@debarghya472

<p><b>Infinito</b> is the annual sports fest of <b>IIT Patna</b>. Over the years, it has proved to be one of the best and the most awaited sports fest around the state. It has made an exponential growth in a very short span of time, gathering considerable media attention.</p>
<p>This year, <b>Infinito</b>, against all odds, continues to keep its legacy alive by managing to keep the fest fully virtual. There will be many online games this year, including some very insightful guest talks. You surely would not want to miss these exhilarating things!</p>
<p><b>Infinito</b> gives you a platform to showcase your skills. Every time you win or lose, you learn something new. We, at <b>Infinito</b>, try our best to give you an experience worth cherishing and some beautiful memories to treasure forever!</p>
<i>So, don't be afraid in trying new things. You never know what you can do until you try.</i>

**Comment by debarghya472** [comment]
Cool create a PR by today
