### ISSUE TITLE
Change image of below mentioned place

### ISSUE THREAD

**Issue by Darshilp326** [Infinito-IIT-Patna/Infinito2020#3]
![Screenshot (163)](https://user-images.githubusercontent.com/55157259/103031991-f8f90100-4584-11eb-89e6-d4c0001bd18d.png)

**Comment by 4d4r5h** [comment]
I want to do this.

**Comment by manavgondalia** [comment]
i have a design for a great image. can i do this

**Comment by debarghya472** [comment]
@manavgondalia go ahead!

**Comment by manavgondalia** [comment]
![bg_2](https://user-images.githubusercontent.com/72291135/103088428-cd235d00-4610-11eb-8da2-5d5e6b905d0f.png)


how about this photo

**Comment by Darshilp326** [comment]
@manavgondalia I will ask CND team and tell u!

**Comment by Darshilp326** [comment]
@manavgondalia they would be giving!

**Comment by manavgondalia** [comment]
okay so i have to wait and put their photo, right?

**Comment by Darshilp326** [comment]
Sadly yes.
I will try to give you by today night

**Comment by debarghya472** [comment]
@manavgondalia  u have already claimed an issue so I'm reassigning it to @padmaja2305

**Comment by debarghya472** [comment]
@padmaja2305 comment here to claim ur issue

**Comment by padmaja2305** [comment]
Can I try this one?

**Comment by padmaja2305** [comment]
![image](https://user-images.githubusercontent.com/72041195/103152662-37263880-47b0-11eb-94da-8ec704612b34.png)

**Comment by padmaja2305** [comment]
is it ok?

**Comment by padmaja2305** [comment]
![image](https://user-images.githubusercontent.com/72041195/103152832-a94b4d00-47b1-11eb-8cae-27f9e5f2137a.png)

**Comment by padmaja2305** [comment]
is it ok?

**Comment by debarghya472** [comment]
Nice! just decrease the image size to fit the position and open a PR(create a new branch)

**Comment by padmaja2305** [comment]
![image](https://user-images.githubusercontent.com/72041195/103154867-c0de0200-47c0-11eb-9872-c4b212385d82.png)
will this size do?

**Comment by debarghya472** [comment]
closes issue #3
