### ISSUE TITLE
Replace with recent posts from Social Media

### ISSUE THREAD

**Issue by debarghya472** [Infinito-IIT-Patna/Infinito2020#31]
<img width="1440" alt="Screenshot 2020-12-29 at 10 29 09 PM" src="https://user-images.githubusercontent.com/54908977/103300774-b83a3580-4a25-11eb-858f-550d2ef3bd27.png">

All you have to do is take ss and replace the link of some of recent posts by Infinito IIT Patna
It might be Facebook or Instagram Posts 

Claim this issue fast!!!

**Comment by Code-Aditya-14** [comment]
Can I do this?
