### ISSUE TITLE
Remove updates and current score part from home page

### ISSUE THREAD

**Issue by Darshilp326** [Infinito-IIT-Patna/Infinito2020#7]
Comment out that code!

**Comment by Suyog57** [comment]
Bhaiya, Can I do this but is it only to delete the following or to add something?

**Comment by debarghya472** [comment]
You have to comment out that part of code.

**Comment by Code-Aditya-14** [comment]
If this work is not done then can I do this? And I only have to comment out the scores section from home page?

**Comment by Darshilp326** [comment]
@Code-Aditya-14 do it
