### ISSUE TITLE
Change tagline and upload a new picture in below mentioned place

### ISSUE THREAD

**Issue by Darshilp326** [Infinito-IIT-Patna/Infinito2020#8]
![Screenshot (165)](https://user-images.githubusercontent.com/55157259/103032402-f519ae80-4585-11eb-8099-97837cae9b5f.png)

**Comment by manavgondalia** [comment]
may I do this one

**Comment by Darshilp326** [comment]
Go for it

**Comment by Darshilp326** [comment]
@manavgondalia  change tagline to feel the burn

**Comment by manavgondalia** [comment]
@Darshilp326 ok and the photo can be inserted by me or will i get a photo
because i am creating one...

**Comment by manavgondalia** [comment]
And i thought of some other taglines as well like:
1- Hustle and heart set us apart.
2- Get your Game on.
3- Go big or go home.
4- Take your seats.
just suggesting these...

**Comment by manavgondalia** [comment]
![bg_1](https://user-images.githubusercontent.com/72291135/103088020-7bc69e00-460f-11eb-820d-3fc3e7bfaf27.png)

should i upload this in the bg

**Comment by manavgondalia** [comment]
![bg_3](https://user-images.githubusercontent.com/72291135/103089467-027d7a00-4614-11eb-831f-b981bd2c85c3.png)

was talking about this image
for the bg

**Comment by Darshilp326** [comment]
@manavgondalia photo is good but select any team photo from drive!

**Comment by manavgondalia** [comment]
ok, no problem
