### ISSUE TITLE
Add linkedin and change our logo in footer

### ISSUE THREAD

**Issue by Darshilp326** [Infinito-IIT-Patna/Infinito2020#9]
![Screenshot (166)](https://user-images.githubusercontent.com/55157259/103032569-622d4400-4586-11eb-9532-ac9df80b94c7.png)

**Comment by Darshilp326** [comment]
Add youtube also!

**Comment by programmerraja** [comment]
@debarghya472 
Can I work on this bro ✌️

**Comment by padmaja2305** [comment]
Can I try this?

**Comment by debarghya472** [comment]
@padmaja2305 this issue is already claimed why @programmerraja
